## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("C:/Users/Juana/Desktop/GWU/Class_Lessons/Mod6_PythonAPIs/Mod6_Challenge/Weather_Database/WeatherPy_Database.csv", index_col=[0])
city_data_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather description
City_ID,,,,,,,,,
0,Kualakapuas,ID,-3.0091,114.3876,74.84,96,99,2.46,overcast clouds
1,Avarua,CK,-21.2078,-159.7750,75.25,83,75,11.50,broken clouds
2,Bredasdorp,ZA,-34.5322,20.0403,54.36,64,100,7.85,overcast clouds
3,Hithadhoo,MV,-0.6000,73.0833,81.09,74,100,7.18,overcast clouds
4,Adrar,MR,20.5022,-10.0711,98.38,28,59,3.00,light rain
5,Port Alfred,ZA,-33.5906,26.8910,65.50,67,49,3.33,scattered clouds
6,Salalah,OM,17.0151,54.0924,78.89,89,75,9.22,broken clouds
7,Tuktoyaktuk,CA,69.4541,-133.0374,56.37,71,86,6.80,overcast clouds
8,Hermanus,ZA,-34.4187,19.2345,57.79,68,92,11.77,overcast clouds
9,Mocuba,MZ,-16.8392,36.9856,68.58,72,31,6.49,scattered clouds

In [25]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 100

In [26]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather description
City_ID,,,,,,,,,
1,Avarua,CK,-21.2078,-159.7750,75.25,83,75,11.50,broken clouds
3,Hithadhoo,MV,-0.6000,73.0833,81.09,74,100,7.18,overcast clouds
4,Adrar,MR,20.5022,-10.0711,98.38,28,59,3.00,light rain
6,Salalah,OM,17.0151,54.0924,78.89,89,75,9.22,broken clouds
11,Jamestown,US,42.0970,-79.2353,82.94,70,4,1.99,clear sky
23,Isangel,VU,-19.5500,169.2667,75.92,87,100,10.51,overcast clouds
26,Faanui,PF,-16.4833,-151.7500,77.65,74,13,10.29,few clouds
28,Makasar,ID,-5.1400,119.4221,75.25,100,20,3.44,few clouds
29,Onverwacht,SR,5.5833,-55.1833,87.80,68,40,3.44,scattered clouds
32,Albany,US,42.6001,-73.9662,92.43,41,7,1.01,clear sky

In [27]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City                   322
Country                322
Lat                    322
Lng                    322
Max Temp               322
Humidity               322
Cloudiness             322
Wind Speed             322
Weather description    322
dtype: int64

In [28]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna(how ='all')
preferred_cities_df.head(50)

,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather description
City_ID,,,,,,,,,
1,Avarua,CK,-21.2078,-159.7750,75.25,83,75,11.50,broken clouds
3,Hithadhoo,MV,-0.6000,73.0833,81.09,74,100,7.18,overcast clouds
4,Adrar,MR,20.5022,-10.0711,98.38,28,59,3.00,light rain
6,Salalah,OM,17.0151,54.0924,78.89,89,75,9.22,broken clouds
11,Jamestown,US,42.0970,-79.2353,82.94,70,4,1.99,clear sky
23,Isangel,VU,-19.5500,169.2667,75.92,87,100,10.51,overcast clouds
26,Faanui,PF,-16.4833,-151.7500,77.65,74,13,10.29,few clouds
28,Makasar,ID,-5.1400,119.4221,75.25,100,20,3.44,few clouds
29,Onverwacht,SR,5.5833,-55.1833,87.80,68,40,3.44,scattered clouds
32,Albany,US,42.6001,-73.9662,92.43,41,7,1.01,clear sky
40,San Pedro Del Parana,PY,-26.8333,-56.2000,81.07,50,69,7.67,broken clouds
41,Taitung,TW,22.7583,121.1444,82.67,79,69,5.37,broken clouds
43,Arraial Do Cabo,BR,-22.9661,-42.0278,78.76,73,0,13.80,clear sky
47,San Patricio,US,28.0170,-97.5169,93.06,41,92,14.14,overcast clouds
50,Ponta Do Sol,PT,32.6667,-17.1000,75.83,58,0,3.71,clear sky
51,La Macarena,CO,2.1837,-73.7849,89.08,48,34,1.59,scattered clouds
54,Non Thai,TH,15.1981,102.0358,81.03,88,100,3.67,overcast clouds
55,Olinda,BR,-8.0089,-34.8553,80.33,69,40,13.80,scattered clouds
56,Hilo,US,19.7297,-155.0900,77.29,97,100,6.91,mist
63,Kasangulu,CD,-4.5911,15.1708,83.91,45,88,6.55,overcast clouds
69,Ocos,GT,14.5094,-92.1933,82.54,73,45,6.04,scattered clouds
70,Bathsheba,BB,13.2167,-59.5167,85.05,83,10,16.17,clear sky
71,Kahului,US,20.8947,-156.4700,76.84,85,2,7.00,clear sky
73,Eyl,SO,7.9803,49.8164,77.94,78,99,26.33,overcast clouds
79,Benito Juarez,MX,19.3850,-99.1650,77.94,51,80,1.99,broken clouds
80,Tual,ID,-5.6667,132.7500,77.38,77,69,13.91,broken clouds
81,Cockburn Town,TC,21.4612,-71.1419,78.96,86,100,20.09,overcast clouds
82,Kutum,SD,14.2000,24.6667,87.40,28,11,7.65,few clouds
85,Bengkulu,ID,-3.8004,102.2655,75.81,89,87,4.68,overcast clouds
86,Hamilton,US,39.1834,-84.5333,91.74,60,1,4.00,clear sky
88,Touros,BR,-5.1989,-35.4608,82.20,68,92,15.03,overcast clouds
91,Ribeira Grande,PT,38.5167,-28.7000,77.40,83,40,12.66,scattered clouds
92,Dicabisagan,PH,17.0818,122.4157,79.81,89,62,2.08,broken clouds
94,Qui Nhon,VN,13.7667,109.2333,77.79,85,99,2.15,overcast clouds
95,Broome,US,42.2506,-75.8330,87.19,54,3,8.99,clear sky
97,Forestville,US,38.8451,-76.8750,95.22,45,0,1.99,clear sky
98,Butaritari,KI,3.0707,172.7902,80.96,76,30,9.19,scattered clouds
100,Odienne,CI,9.5100,-7.5692,80.58,78,89,2.64,light rain
101,Arrecife,ES,28.9630,-13.5477,85.98,54,20,14.97,few clouds
102,Bethel,US,41.3712,-73.4140,93.34,47,0,3.00,clear sky
106,Columbus,US,39.9612,-82.9988,89.11,62,40,9.22,scattered clouds
107,Tadine,NC,-21.5500,167.8833,75.29,88,100,16.08,overcast clouds
111,Nizwa,OM,22.9333,57.5333,91.67,55,52,1.72,broken clouds
112,Buala,SB,-8.1450,159.5921,78.98,81,8,4.74,clear sky
113,Dingle,PH,10.9995,122.6711,77.00,90,75,4.50,broken clouds
114,Tenenkou,ML,14.4572,-4.9169,92.55,39,99,0.63,overcast clouds
116,Devils Lake,US,48.1128,-98.8651,78.91,60,24,5.99,few clouds
118,Caravelas,BR,-17.7125,-39.2481,76.84,69,40,5.88,scattered clouds
119,Linguere,SN,15.3953,-15.1193,80.82,94,75,4.61,broken clouds
120,Venice,US,27.0998,-82.4543,95.14,57,75,12.66,broken clouds

In [29]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Weather description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Weather description,Lat,Lng,Hotel Name
City_ID,,,,,,,
1,Avarua,CK,75.25,broken clouds,-21.2078,-159.7750,
3,Hithadhoo,MV,81.09,overcast clouds,-0.6000,73.0833,
4,Adrar,MR,98.38,light rain,20.5022,-10.0711,
6,Salalah,OM,78.89,broken clouds,17.0151,54.0924,
11,Jamestown,US,82.94,clear sky,42.0970,-79.2353,
23,Isangel,VU,75.92,overcast clouds,-19.5500,169.2667,
26,Faanui,PF,77.65,few clouds,-16.4833,-151.7500,
28,Makasar,ID,75.25,few clouds,-5.1400,119.4221,
29,Onverwacht,SR,87.80,scattered clouds,5.5833,-55.1833,
32,Albany,US,92.43,clear sky,42.6001,-73.9662,

In [30]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():

    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [32]:
#7a Create new csv file
output_data_file = "WeatherPy_hotel.csv"
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [33]:
# 7b Bring in new data frame
clean_hotel_df = pd.read_csv("C:/Users/Juana/Desktop/GWU/Class_Lessons/Mod6_PythonAPIs/Mod6_Challenge/Vacation_Search/WeatherPy_hotel.csv", index_col=[0])
clean_hotel_df.head(50)

,City,Country,Max Temp,Weather description,Lat,Lng,Hotel Name
City_ID,,,,,,,
1,Avarua,CK,75.25,broken clouds,-21.2078,-159.7750,Paradise Inn
3,Hithadhoo,MV,81.09,overcast clouds,-0.6000,73.0833,Scoop Guest House
4,Adrar,MR,98.38,light rain,20.5022,-10.0711,NaN
6,Salalah,OM,78.89,broken clouds,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
11,Jamestown,US,82.94,clear sky,42.0970,-79.2353,Hampton Inn & Suites Jamestown
23,Isangel,VU,75.92,overcast clouds,-19.5500,169.2667,Tanna Lodge
26,Faanui,PF,77.65,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
28,Makasar,ID,75.25,few clouds,-5.1400,119.4221,Aryaduta Makassar
29,Onverwacht,SR,87.80,scattered clouds,5.5833,-55.1833,"Overtoom, District Para, Paramaribo"
32,Albany,US,92.43,clear sky,42.6001,-73.9662,NaN
40,San Pedro Del Parana,PY,81.07,broken clouds,-26.8333,-56.2000,Hotel Oasis
41,Taitung,TW,82.67,broken clouds,22.7583,121.1444,Taitung Bali Suites Hotel
43,Arraial Do Cabo,BR,78.76,clear sky,-22.9661,-42.0278,Pousada Porto Praia
47,San Patricio,US,93.06,overcast clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
50,Ponta Do Sol,PT,75.83,clear sky,32.6667,-17.1000,Hotel do Campo
51,La Macarena,CO,89.08,scattered clouds,2.1837,-73.7849,Casa Hotel Real
54,Non Thai,TH,81.03,overcast clouds,15.1981,102.0358,ครัวพี่หนุ่ม สงต่อน
55,Olinda,BR,80.33,scattered clouds,-8.0089,-34.8553,Flat Quatro Rodas Olinda
56,Hilo,US,77.29,mist,19.7297,-155.0900,Hilo Hawaiian Hotel
63,Kasangulu,CD,83.91,overcast clouds,-4.5911,15.1708,Hôtel le Relais
69,Ocos,GT,82.54,scattered clouds,14.5094,-92.1933,Auto Hotel El Soñador
70,Bathsheba,BB,85.05,clear sky,13.2167,-59.5167,Atlantis Hotel
71,Kahului,US,76.84,clear sky,20.8947,-156.4700,Maui Seaside Hotel
73,Eyl,SO,77.94,overcast clouds,7.9803,49.8164,Amiin Hotel
79,Benito Juarez,MX,77.94,broken clouds,19.3850,-99.1650,Hotel Beverly
80,Tual,ID,77.38,broken clouds,-5.6667,132.7500,Grand Vilia Hotel
81,Cockburn Town,TC,78.96,overcast clouds,21.4612,-71.1419,Osprey Beach Hotel
82,Kutum,SD,87.40,few clouds,14.2000,24.6667,Dibbo areaمنطقة دبو
85,Bengkulu,ID,75.81,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
86,Hamilton,US,91.74,clear sky,39.1834,-84.5333,Six Acres Bed & Breakfast
88,Touros,BR,82.20,overcast clouds,-5.1989,-35.4608,INN NEW HORIZON
91,Ribeira Grande,PT,77.40,scattered clouds,38.5167,-28.7000,Quinta da Meia Eira
92,Dicabisagan,PH,79.81,broken clouds,17.0818,122.4157,Nancy Montanes Bernardo
94,Qui Nhon,VN,77.79,overcast clouds,13.7667,109.2333,Seagull Hotel
95,Broome,US,87.19,clear sky,42.2506,-75.8330,Chenango Valley State Park
97,Forestville,US,95.22,clear sky,38.8451,-76.8750,Quality Inn Near Joint Base Andrews-Washington...
98,Butaritari,KI,80.96,scattered clouds,3.0707,172.7902,Isles Sunset Lodge
100,Odienne,CI,80.58,light rain,9.5100,-7.5692,Oustaz Vame DIAKITE
101,Arrecife,ES,85.98,few clouds,28.9630,-13.5477,Hotel Lancelot
102,Bethel,US,93.34,clear sky,41.3712,-73.4140,Courtyard by Marriott Danbury
106,Columbus,US,89.11,scattered clouds,39.9612,-82.9988,DoubleTree Suites by Hilton Hotel Columbus Dow...
107,Tadine,NC,75.29,overcast clouds,-21.5500,167.8833,NaN
111,Nizwa,OM,91.67,broken clouds,22.9333,57.5333,Orient Apartments
112,Buala,SB,78.98,clear sky,-8.1450,159.5921,Maringe Lagoon Lodge
113,Dingle,PH,77.00,broken clouds,10.9995,122.6711,SEGAYA PROPERTY
114,Tenenkou,ML,92.55,overcast clouds,14.4572,-4.9169,NaN
116,Devils Lake,US,78.91,few clouds,48.1128,-98.8651,"Holiday Inn Express Devils Lake, an IHG Hotel"
118,Caravelas,BR,76.84,scattered clouds,-17.7125,-39.2481,Pousada dos Navegantes
119,Linguere,SN,80.82,broken clouds,15.3953,-15.1193,AYO Casablanca
120,Venice,US,95.14,broken clouds,27.0998,-82.4543,A Beach Retreat On Casey Key

In [34]:
# 7c Drop the rows where there is no Hotel Name.
#clean_hotel_df = hotel_df.copy()
#clean_hotel_df.['Hotel Name'].fillna('')
clean_hotel_df.dropna(subset = ['Hotel Name'], inplace = True)
clean_hotel_df.head(50)

,City,Country,Max Temp,Weather description,Lat,Lng,Hotel Name
City_ID,,,,,,,
1,Avarua,CK,75.25,broken clouds,-21.2078,-159.7750,Paradise Inn
3,Hithadhoo,MV,81.09,overcast clouds,-0.6000,73.0833,Scoop Guest House
6,Salalah,OM,78.89,broken clouds,17.0151,54.0924,"HAMDAN PLAZA HOTEL SALALAH, an HTG Hotel"
11,Jamestown,US,82.94,clear sky,42.0970,-79.2353,Hampton Inn & Suites Jamestown
23,Isangel,VU,75.92,overcast clouds,-19.5500,169.2667,Tanna Lodge
26,Faanui,PF,77.65,few clouds,-16.4833,-151.7500,Bora-Bora Pearl Beach Resort & Spa
28,Makasar,ID,75.25,few clouds,-5.1400,119.4221,Aryaduta Makassar
29,Onverwacht,SR,87.80,scattered clouds,5.5833,-55.1833,"Overtoom, District Para, Paramaribo"
40,San Pedro Del Parana,PY,81.07,broken clouds,-26.8333,-56.2000,Hotel Oasis
41,Taitung,TW,82.67,broken clouds,22.7583,121.1444,Taitung Bali Suites Hotel
43,Arraial Do Cabo,BR,78.76,clear sky,-22.9661,-42.0278,Pousada Porto Praia
47,San Patricio,US,93.06,overcast clouds,28.0170,-97.5169,"Motel 6 Sinton, TX"
50,Ponta Do Sol,PT,75.83,clear sky,32.6667,-17.1000,Hotel do Campo
51,La Macarena,CO,89.08,scattered clouds,2.1837,-73.7849,Casa Hotel Real
54,Non Thai,TH,81.03,overcast clouds,15.1981,102.0358,ครัวพี่หนุ่ม สงต่อน
55,Olinda,BR,80.33,scattered clouds,-8.0089,-34.8553,Flat Quatro Rodas Olinda
56,Hilo,US,77.29,mist,19.7297,-155.0900,Hilo Hawaiian Hotel
63,Kasangulu,CD,83.91,overcast clouds,-4.5911,15.1708,Hôtel le Relais
69,Ocos,GT,82.54,scattered clouds,14.5094,-92.1933,Auto Hotel El Soñador
70,Bathsheba,BB,85.05,clear sky,13.2167,-59.5167,Atlantis Hotel
71,Kahului,US,76.84,clear sky,20.8947,-156.4700,Maui Seaside Hotel
73,Eyl,SO,77.94,overcast clouds,7.9803,49.8164,Amiin Hotel
79,Benito Juarez,MX,77.94,broken clouds,19.3850,-99.1650,Hotel Beverly
80,Tual,ID,77.38,broken clouds,-5.6667,132.7500,Grand Vilia Hotel
81,Cockburn Town,TC,78.96,overcast clouds,21.4612,-71.1419,Osprey Beach Hotel
82,Kutum,SD,87.40,few clouds,14.2000,24.6667,Dibbo areaمنطقة دبو
85,Bengkulu,ID,75.81,overcast clouds,-3.8004,102.2655,Grage Hotel Bengkulu
86,Hamilton,US,91.74,clear sky,39.1834,-84.5333,Six Acres Bed & Breakfast
88,Touros,BR,82.20,overcast clouds,-5.1989,-35.4608,INN NEW HORIZON
91,Ribeira Grande,PT,77.40,scattered clouds,38.5167,-28.7000,Quinta da Meia Eira
92,Dicabisagan,PH,79.81,broken clouds,17.0818,122.4157,Nancy Montanes Bernardo
94,Qui Nhon,VN,77.79,overcast clouds,13.7667,109.2333,Seagull Hotel
95,Broome,US,87.19,clear sky,42.2506,-75.8330,Chenango Valley State Park
97,Forestville,US,95.22,clear sky,38.8451,-76.8750,Quality Inn Near Joint Base Andrews-Washington...
98,Butaritari,KI,80.96,scattered clouds,3.0707,172.7902,Isles Sunset Lodge
100,Odienne,CI,80.58,light rain,9.5100,-7.5692,Oustaz Vame DIAKITE
101,Arrecife,ES,85.98,few clouds,28.9630,-13.5477,Hotel Lancelot
102,Bethel,US,93.34,clear sky,41.3712,-73.4140,Courtyard by Marriott Danbury
106,Columbus,US,89.11,scattered clouds,39.9612,-82.9988,DoubleTree Suites by Hilton Hotel Columbus Dow...
111,Nizwa,OM,91.67,broken clouds,22.9333,57.5333,Orient Apartments
112,Buala,SB,78.98,clear sky,-8.1450,159.5921,Maringe Lagoon Lodge
113,Dingle,PH,77.00,broken clouds,10.9995,122.6711,SEGAYA PROPERTY
116,Devils Lake,US,78.91,few clouds,48.1128,-98.8651,"Holiday Inn Express Devils Lake, an IHG Hotel"
118,Caravelas,BR,76.84,scattered clouds,-17.7125,-39.2481,Pousada dos Navegantes
119,Linguere,SN,80.82,broken clouds,15.3953,-15.1193,AYO Casablanca
120,Venice,US,95.14,broken clouds,27.0998,-82.4543,A Beach Retreat On Casey Key
122,Kirakira,SB,77.43,few clouds,-10.4544,161.9205,SanBiz Lodge
123,Crossville,US,86.02,few clouds,35.9490,-85.0269,Hampton Inn Crossville
125,Torbay,CA,78.89,overcast clouds,47.6666,-52.7314,Gallows Cove
126,Cabo San Lucas,MX,86.25,overcast clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos

In [35]:
# 7d Determine if there are any empty rows.
clean_hotel_df.count()

City                   302
Country                302
Max Temp               302
Weather description    302
Lat                    302
Lng                    302
Hotel Name             302
dtype: int64

In [36]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [37]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Weather description</dt><dd>{Weather description}<dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
clean_hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [38]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=2)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
                                 dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations, info_box_content=clean_hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))